set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]

set_property LOC T28 [get_ports led[0]]
set_property LOC V19 [get_ports led[1]]
set_property LOC U30 [get_ports led[2]]
set_property LOC U29 [get_ports led[3]]
set_property LOC V20 [get_ports led[4]]


set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[4]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[5]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[6]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[7]]

set_property LOC G19 [get_ports sw[0]]
set_property LOC G25 [get_ports sw[1]]
set_property LOC H24 [get_ports sw[2]]
set_property LOC K19 [get_ports sw[3]]
set_property LOC N19 [get_ports sw[4]]
set_property LOC P19 [get_ports sw[5]]
set_property LOC P26 [get_ports sw[6]]
set_property LOC P27 [get_ports sw[7]]
